const BOOKING='https://n304612.yclients.com/';
const programs=[
 {icon:'🫧',title:'Грудничковое плавание',age:'от 1 месяца до 1 года',text:'Адаптация ребёнка к водной среде, навыки ныряния, дыхания и расслабления.'},
 {icon:'🐳',title:'Раннее плавание',age:'от 1 года до 3 лет',text:'Интенсивные игровые занятия, любовь к воде и первые навыки самостоятельного плавания.'},
 {icon:'⭐',title:'Дошкольное плавание',age:'от 3 до 5 лет',text:'Подготовка к уверенному плаванию: кроль на спине и груди, брасс и баттерфляй.'},
 {icon:'🥽',title:'Школьное плавание',age:'от 5 до 10 лет',text:'Базовые техники, физическая подготовка, выносливость и подготовка к большому бассейну.'},
 {icon:'💙',title:'Коррекционное плавание',age:'индивидуально',text:'Водная реабилитация для детей с ограниченными возможностями здоровья.'},
 {icon:'👨‍👩‍👧',title:'Вместе с мамой или папой',age:'от 1 месяца до 3 лет',text:'Родитель занимается вместе с малышом в воде под мягким руководством тренера.'},
 {icon:'🧘‍♀️',title:'Аква-йога и акмионика',age:'для будущих мам',text:'Дыхание, расслабление и физическая активность как основа хорошего самочувствия.'},
 {icon:'🌊',title:'Свободное плавание',age:'30 минут — 2 500 ₽',text:'Самостоятельное плавание родителя и ребёнка без присутствия тренера.'}
];
const trainers=[
 {name:'Эльвира',img:'trainer-elvira.webp',role:'Грудничковое, раннее, дошкольное и восстановительное плавание',quote:'Слышу ребёнка, чувствую воду — сопровождаю к осознанному плаванию.'},
 {name:'Алина',img:'trainer-alina.webp',role:'Грудничковое, раннее, дошкольное и реабилитационное плавание',quote:'Современные методики и увлекательные занятия — здоровье без границ.'},
 {name:'Полина',img:'trainer-polina.webp',role:'Грудничковое, раннее и дошкольное плавание',quote:'Вместо правил — доверие. Вместо гребков — радость.'},
 {name:'Сергей',img:'trainer-sergey.webp',role:'Грудничковое, раннее, дошкольное и восстановительное плавание',quote:'Каждый ребёнок уникален, каждое занятие особенное.'},
 {name:'Наталья',img:'trainer-natalya.webp',role:'Грудничковое, раннее, дошкольное и восстановительное плавание',quote:'Не заставляю, а увлекаю. Вода должна быть в радость.'}
];
const pages={
 home:()=>`<main><section class="hero"><div class="container hero-grid"><div><span class="eyebrow">От 1 месяца до 10 лет</span><h1>Детский бассейн индивидуального плавания <span>Пробное занятие — 1 500 ₽</span></h1><p class="lead">Тёплая вода, внимательный тренер и безопасная среда, в которой ребёнок учится любить воду.</p><div class="actions"><a class="btn coral" href="${BOOKING}">Записаться на пробное</a><a class="btn secondary" href="programs.html">Выбрать программу</a></div></div><div class="hero-photo"><img src="assets/images/pool-wide.webp" alt="Бассейн Кашалотик"></div></div></section>${trustbar()}<section><div class="container"><div class="section-head"><div><span class="eyebrow">Программы</span><h2>Плавание в своём темпе</h2></div><p>От мягкого знакомства с водой до освоения спортивных стилей.</p></div><div class="cards">${programs.slice(0,4).map(programCard).join('')}</div><div class="actions"><a class="btn secondary" href="programs.html">Все программы</a></div></div></section>${safetyFeature()}${trainerSection()}${priceSection()}${gallery()}${cta()}</main>`,
 programs:()=>`<main>${pageHero('Программы','Занятия, которые растут вместе с ребёнком','Каждая программа адаптируется под возраст, состояние здоровья и индивидуальные особенности ребёнка.')}<section><div class="container program-list">${programs.map(p=>`<article class="program-row reveal"><div class="program-symbol">${p.icon}</div><div><span class="age">${p.age}</span><h2>${p.title}</h2><p>${p.text}</p></div><a class="btn" href="${BOOKING}">Записаться</a></article>`).join('')}</div></section>${cta()}</main>`,
 prices:()=>`<main>${pageHero('Цены','Понятная стоимость без скрытых условий','Индивидуальные занятия продолжительностью 30 или 45 минут.')}<section><div class="container">${priceSection(true)}<div class="section-head" style="margin-top:70px"><div><span class="eyebrow">45 минут</span><h2>Продлённые занятия</h2></div></div><div class="table-wrap"><table><thead><tr><th>Формат</th><th>Стоимость</th><th>Одно занятие</th><th>Срок действия</th></tr></thead><tbody><tr><td>Разовое занятие</td><td>4 500 ₽</td><td>4 500 ₽</td><td>—</td></tr><tr><td>4 занятия</td><td>13 400 ₽</td><td>3 350 ₽</td><td>30 дней</td></tr><tr><td>8 занятий</td><td>25 600 ₽</td><td>3 200 ₽</td><td>30 дней</td></tr><tr><td>12 занятий</td><td>37 200 ₽</td><td>3 100 ₽</td><td>45 дней</td></tr></tbody></table></div><div class="notice" style="margin-top:28px"><b>Важно:</b> предоплата за пробное занятие — 1 000 ₽. Перенос или отмену нужно оформить до 20:00 предшествующего дня.</div><div class="section-head" style="margin-top:70px"><div><span class="eyebrow">Ранние рыбки</span><h2>Будни с 9:00 до 14:00</h2></div></div><div class="price-grid"><div class="price"><h3>4 занятия</h3><div class="amount">8 600 ₽</div><p>2 150 ₽ за занятие · 30 дней</p></div><div class="price"><h3>8 занятий</h3><div class="amount">15 840 ₽</div><p>1 980 ₽ за занятие · 30 дней</p></div><div class="price"><h3>12 занятий</h3><div class="amount">22 680 ₽</div><p>1 890 ₽ за занятие · 45 дней · заморозка 14 дней</p></div></div><div class="section-head" style="margin-top:70px"><div><span class="eyebrow">Акции</span><h2>Поддерживаем семьи</h2></div></div><div class="cards"><div class="card"><div class="icon">10%</div><h3>Детям с ОВЗ</h3><p>Скидка на занятия для детей с ограниченными возможностями здоровья.</p></div><div class="card"><div class="icon">10%</div><h3>Многодетным семьям</h3><p>Скидка на занятия при подтверждении статуса.</p></div><div class="card"><div class="icon">🎁</div><h3>В день пробного</h3><p>При покупке 8 или 12 занятий пробное в подарок; на 4 занятия — скидка 50% на пробное.</p></div><div class="card"><div class="icon">10%</div><h3>Пригласи друга</h3><p>Предложение для владельцев действующих абонементов.</p></div></div></div></section>${cta()}</main>`,
 trainers:()=>`<main>${pageHero('Команда','Тренеры, которые слышат ребёнка','Профессионалы, искренне любящие детей и посвятившие себя детскому плаванию.')}<section><div class="container"><div class="trainers">${trainers.map(trainerCard).join('')}</div><div class="notice" style="margin-top:32px">Тренер подбирает темп и методику под возраст, характер и текущие навыки ребёнка.</div></div></section>${cta()}</main>`,
 safety:()=>`<main>${pageHero('Безопасность воды','Чистая вода — наша главная забота','Система водоподготовки работает круглосуточно и полностью обновляет воду бассейна каждые два часа.')}<section><div class="container feature"><div><h2>Пять ступеней водоподготовки</h2><div class="steps"><div class="step"><h3>Грубая очистка</h3><p>Механическая фильтрация циркулирующей воды.</p></div><div class="step"><h3>Тонкая очистка</h3><p>Самостерилизующееся кварцевое стекло эффективнее стандартного песка.</p></div><div class="step"><h3>Обеззараживание</h3><p>Автоматическое хлорирование в безопасной концентрации и УФ-облучение.</p></div><div class="step"><h3>Контроль pH</h3><p>Постоянный электронный анализ и диапазон 7,2–7,6.</p></div><div class="step"><h3>Подогрев</h3><p>Комфортная температура воды 32–34 °C.</p></div></div></div><img src="assets/images/pool-toy.webp" alt="Инвентарь в бассейне Кашалотик"></div></section><section><div class="container content"><h2>Соответствие требованиям</h2><p>Водоподготовка соответствует СанПиН 2.1.3678-20. Автоматическая станция работает 24 часа в сутки, обеспечивая необходимый водообмен и контроль качества.</p><div class="notice">Комбинированный метод очистки и обеззараживания безопасен для детей и позволяет максимально снизить остаточную концентрацию хлора.</div></div></section>${cta()}</main>`,
 rules:()=>`<main>${pageHero('Правила','Комфорт и безопасность начинаются с простых правил','Они едины для всех гостей и помогают сохранять воду чистой, а занятия — спокойными.')}<section><div class="container content"><h2>Перед занятием</h2><ol><li>Снимите верхнюю одежду и уличную обувь, переобуйтесь.</li><li>Если до занятия больше 10 минут, можно пройти в игровую комнату.</li><li>Перед бассейном обязательно примите душ с мылом без купального костюма.</li><li>После душа наденьте купальный костюм, сланцы и шапочку.</li><li>Заходите в воду только после приглашения тренера.</li></ol><h2>После занятия</h2><p>Примите душ, насухо вытрите ребёнка, высушите волосы. После этого можно отдохнуть в игровой комнате.</p><h2>Перенос и отмена</h2><div class="notice">Сообщите о переносе или отмене до 20:00 накануне занятия. Отмена день в день не предусмотрена — занятие считается проведённым.</div><h2>Что взять с собой</h2><ul><li>Купальный костюм или плавки</li><li>Шапочку и сменную обувь</li><li>Полотенце, мыло и принадлежности для душа</li><li>Для малышей — специальные подгузники для плавания</li><li>Абонемент</li></ul></div></section>${cta()}</main>`,
 contacts:()=>`<main>${pageHero('Контакты','Загляните к нам','Мы работаем ежедневно и будем рады познакомить ребёнка с водой.')}<section><div class="container contact-grid"><div class="contact-card"><span class="eyebrow">Адрес</span><h2>Россошанский проезд, 3</h2><p>ТЦ «Прага», цокольный этаж<br>Москва</p><p><b>Ежедневно с 9:00 до 21:00</b></p><div class="actions"><a class="btn" href="https://yandex.ru/maps/org/kashalotik/117749875078/">Открыть в Яндекс Картах</a></div></div><div class="contact-card"><span class="eyebrow">Связаться</span><h2><a href="tel:+79259800017">+7 (925) 980-00-17</a></h2><p><a href="mailto:baby_swim@mail.ru">baby_swim@mail.ru</a></p><div class="actions"><a class="btn coral" href="${BOOKING}">Онлайн-запись</a></div></div></div></section><section><div class="container faq"><div class="section-head"><h2>Частые вопросы</h2></div><details><summary>Сколько длится занятие?</summary><p>Индивидуальные занятия проходят 30 или 45 минут.</p></details><details><summary>Могут ли родители наблюдать?</summary><p>Да, родители находятся возле бассейна или наблюдают за ребёнком из комнаты ожидания.</p></details><details><summary>Как перенести занятие?</summary><p>Сообщите администратору до 20:00 предшествующего дня.</p></details></div></section>${cta()}</main>`
};
function header(page){const nav=[['programs','programs.html','Программы'],['prices','prices.html','Цены'],['trainers','trainers.html','Тренеры'],['safety','safety.html','Безопасность'],['rules','rules.html','Правила'],['contacts','contacts.html','Контакты']];return `<header class="site-header"><div class="container header-row"><a class="logo" href="index.html" aria-label="Кашалотик — на главную"><img src="assets/images/logo.svg" alt="Кашалотик"></a><nav class="nav" id="nav">${nav.map(n=>`<a class="${page===n[0]?'active':''}" href="${n[1]}">${n[2]}</a>`).join('')}</nav><a class="phone" href="tel:+79259800017">+7 (925) 980-00-17</a><a class="btn" href="${BOOKING}">Записаться</a><button class="menu-btn" aria-label="Открыть меню" aria-expanded="false">☰</button></div></header>`}
function footer(){return `<footer class="site-footer"><div class="container"><div class="footer-grid"><div><img class="footer-logo" src="assets/images/logo.svg" alt="Кашалотик"></div><div class="footer-links"><a href="programs.html">Программы</a><a href="prices.html">Цены</a><a href="trainers.html">Тренеры</a><a href="safety.html">Безопасность</a><a href="rules.html">Правила</a><a href="contacts.html">Контакты</a></div><div><b>Россошанский проезд, 3</b><div class="footer-muted">ТЦ «Прага», −1 этаж<br>Ежедневно 9:00–21:00<br><a href="tel:+79259800017">+7 (925) 980-00-17</a></div></div></div><div class="copyright">© Кашалотик, 2026. Информация на сайте не является публичной офертой.</div></div></footer>`}
function pageHero(tag,title,text){return `<section class="page-hero"><div class="container"><span class="eyebrow">${tag}</span><h1>${title}</h1><p>${text}</p></div></section>`}
function trustbar(){return `<div class="container trustbar"><div class="trust"><b>Хорошее место</b><small>Статус Яндекс Карт</small></div><div class="trust"><b>Вода 32–34 °C</b><small>Комфортно для малышей</small></div><div class="trust"><b>Ребёнок + тренер</b><small>Без посторонних</small></div><div class="trust"><b>30 или 45 минут</b><small>Длительность на выбор</small></div></div>`}
function programCard(p){return `<article class="card reveal"><div class="icon">${p.icon}</div><span class="age">${p.age}</span><h3>${p.title}</h3><p>${p.text}</p></article>`}
function safetyFeature(){return `<section><div class="container feature"><div><span class="eyebrow">Безопасность</span><h2>Чистая вода — наша главная забота</h2><ul class="checks"><li>Многоступенчатая фильтрация</li><li>УФ-обеззараживание</li><li>Круглосуточная обработка</li><li>Контроль pH 7,2–7,6</li><li>Полный водообмен каждые 2 часа</li></ul><a class="btn secondary" href="safety.html">Как очищается вода</a></div><img src="assets/images/pool-toy.webp" alt="Бассейн Кашалотик"></div></section>`}
function trainerCard(t){return `<article class="trainer reveal"><img src="assets/images/${t.img}" alt="${t.name}, тренер Кашалотика"><div class="trainer-body"><h3>${t.name}</h3><p>${t.role}</p><p>«${t.quote}»</p></div></article>`}
function trainerSection(){return `<section><div class="container"><div class="section-head"><div><span class="eyebrow">Команда</span><h2>Люди с открытым сердцем</h2></div><a class="btn secondary" href="trainers.html">Познакомиться</a></div><div class="trainers">${trainers.map(trainerCard).join('')}</div></div></section>`}
function priceSection(inner=false){const block=`<div class="section-head"><div><span class="eyebrow">Стоимость</span><h2>Выберите удобный формат</h2></div><p>Чем больше занятий, тем выгоднее стоимость одного посещения.</p></div><div class="price-grid"><article class="price featured"><span class="badge">Первый шаг</span><h3>Пробное</h3><div class="amount">1 500 ₽</div><p>30 минут</p><a class="btn coral" href="${BOOKING}">Записаться</a></article><article class="price"><h3>Разовое</h3><div class="amount">3 000 ₽</div><p>30 минут</p></article><article class="price"><h3>4 занятия</h3><div class="amount">9 400 ₽</div><p>2 350 ₽ / занятие</p></article><article class="price"><h3>8 занятий</h3><div class="amount">17 600 ₽</div><p>2 200 ₽ / занятие</p></article><article class="price"><h3>12 занятий</h3><div class="amount">25 200 ₽</div><p>2 100 ₽ / занятие</p></article></div>${!inner?'<div class="actions"><a class="btn secondary" href="prices.html">Все тарифы и условия</a></div>':''}`;return inner?block:`<section><div class="container">${block}</div></section>`}
function gallery(){return `<section><div class="container"><div class="section-head"><h2>Загляните к нам</h2></div><div class="gallery"><img src="assets/images/pool-gallery-1.webp" alt="Занятие в Кашалотике"><img src="assets/images/pool-gallery-2.webp" alt="Интерьер бассейна"><img src="assets/images/pool-gallery-3.webp" alt="Бассейн для детей"></div></div></section>`}
function cta(){return `<section><div class="container cta"><div><h2>Подарите ребёнку радость плавания</h2><p>Россошанский проезд, 3 · ежедневно 9:00–21:00</p></div><a class="btn coral" href="${BOOKING}">Записаться на пробное</a></div></section>`}
const root=document.getElementById('app');const page=document.body.dataset.page||'home';document.body.insertAdjacentHTML('afterbegin',header(page));root.innerHTML=pages[page]();document.body.insertAdjacentHTML('beforeend',footer());
document.querySelector('.menu-btn').addEventListener('click',e=>{const n=document.getElementById('nav');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))});
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('in')),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
